### ISSUE TITLE
Join failures

### ISSUE THREAD

**Issue by gerfen** [Azure/iotedge-lorawan-starterkit#100]
Using the code form the current master branch (0.3.0)  I am receiving `Error processing the message The given key '6' was not present in the dictionary. ` for devices from one particular device manufacturer.  I asked the manufacturer to set up the devices with this frequency plan[1].  I'm trying to determine if there is something incorrectly configured on the devices or if there is a bug in the gateway code?  Here is a sampling of the logs[2].

Any insight as to where the issue lies would be much appreciated.

Thanks!

--Michael

[1] US frequency plan
````
 {
    "SX1301_conf": {
             "lorawan_public": true,
        "clksrc": 1, /* radio_1 provides clock to concentrator */
        "antenna_gain": 0, /* antenna gain, in dBi */
        "radio_0": {
            "enable": true,
            "type": "SX1257",
            "freq": 902700000,
            "rssi_offset": -166.0,
            "tx_enable": true,
            "tx_freq_min": 902000000,
            "tx_freq_max": 928000000
        },
        "radio_1": {
            "enable": true,
            "type": "SX1257",
            "freq": 903400000,
            "rssi_offset": -166.0,
            "tx_enable": false
        },
        "chan_multiSF_0": {
            /* Lora MAC channel, 125kHz, all SF, 902.3 MHz */
            "enable": true,
            "radio": 0,
            "if": -400000
        },
        "chan_multiSF_1": {
            /* Lora MAC channel, 125kHz, all SF, 902.5 MHz */
            "enable": true,
            "radio": 0,
            "if": -200000
        },
        "chan_multiSF_2": {
            /* Lora MAC channel, 125kHz, all SF, 902.7 MHz */
            "enable": true,
            "radio": 0,
            "if": 0
        },
        "chan_multiSF_3": {
            /* Lora MAC channel, 125kHz, all SF, 902.9 MHz */
            "enable": true,
            "radio": 0,
            "if": 200000
        },
        "chan_multiSF_4": {
            /* Lora MAC channel, 125kHz, all SF, 903.1 MHz */
            "enable": true,
            "radio": 1,
            "if": -300000
        },
        "chan_multiSF_5": {
            /* Lora MAC channel, 125kHz, all SF, 903.3 MHz */
            "enable": true,
            "radio": 1,
            "if": -100000
        },
        "chan_multiSF_6": {
            /* Lora MAC channel, 125kHz, all SF, 903.5 MHz */
            "enable": true,
            "radio": 1,
            "if": 100000
        },
        "chan_multiSF_7": {
            /* Lora MAC channel, 125kHz, all SF, 903.7 MHz */
            "enable": true,
            "radio": 1,
            "if": 300000
        },
        "chan_Lora_std": {
            /* Lora MAC channel, 500kHz, SF8, 903.0 MHz */
            "enable": true,
            "radio": 0,
            "if": 300000,
            "bandwidth": 500000,
            "spread_factor": 8
        },
        "chan_FSK": {
            /* FSK 100kbps channel, 903.0 MHz */
            "enable": false,
            "radio": 0,
            "if": 300000,
            "bandwidth": 250000,
            "datarate": 100000
        },
                "tx_lut_0": {
                        "desc": "TX gain table, index 0",
                        "pa_gain": 0,
                        "mix_gain": 8,
                        "rf_power": -6,
                        "dig_gain": 0
                },
                "tx_lut_1": {
                        "desc": "TX gain table, index 1",
                        "pa_gain": 0,
                        "mix_gain": 10,
                        "rf_power": -3,
                        "dig_gain": 0
                },
                "tx_lut_2": {
                        "desc": "TX gain table, index 2",
                        "pa_gain": 0,
                        "mix_gain": 12,
                        "rf_power": 0,
                        "dig_gain": 0
                },
                "tx_lut_3": {
                        "desc": "TX gain table, index 3",
                        "pa_gain": 1,
                        "mix_gain": 8,
                        "rf_power": 3,
                        "dig_gain": 0
                },
                "tx_lut_4": {
                        "desc": "TX gain table, index 4",
                        "pa_gain": 1,
                        "mix_gain": 10,
                        "rf_power": 6,
                        "dig_gain": 0
                },
                "tx_lut_5": {
                        "desc": "TX gain table, index 5",
                        "pa_gain": 1,
                        "mix_gain": 12,
                        "rf_power": 10,
                        "dig_gain": 0
                },
                "tx_lut_6": {
                        "desc": "TX gain table, index 6",
                        "pa_gain": 1,
                        "mix_gain": 13,
                        "rf_power": 11,
                        "dig_gain": 0
                },
                "tx_lut_7": {
                        "desc": "TX gain table, index 7",
                        "pa_gain": 2,
                        "mix_gain": 9,
                        "rf_power": 12,
                        "dig_gain": 0
                },
                "tx_lut_8": {
                        "desc": "TX gain table, index 8",
                        "pa_gain": 1,
                        "mix_gain": 15,
                        "rf_power": 13,
                        "dig_gain": 0
                },
                "tx_lut_9": {
                        "desc": "TX gain table, index 9",
                        "pa_gain": 2,
                        "mix_gain": 10,
                        "rf_power": 14,
                        "dig_gain": 0
                },
                "tx_lut_10": {
                        "desc": "TX gain table, index 10",
                        "pa_gain": 2,
                        "mix_gain": 11,
                        "rf_power": 16,
                        "dig_gain": 0
                },
                "tx_lut_11": {
                        "desc": "TX gain table, index 11",
                        "pa_gain": 3,
                        "mix_gain": 9,
                        "rf_power": 20,
                        "dig_gain": 0
                },
                "tx_lut_12": {
                        "desc": "TX gain table, index 12",
                        "pa_gain": 3,
                        "mix_gain": 10,
                        "rf_power": 23,
                        "dig_gain": 0
                },
                "tx_lut_13": {
                        "desc": "TX gain table, index 13",
                        "pa_gain": 3,
                        "mix_gain": 11,
                        "rf_power": 25,
                        "dig_gain": 0
                },
                "tx_lut_14": {
                        "desc": "TX gain table, index 14",
                        "pa_gain": 3,
                        "mix_gain": 12,
                        "rf_power": 26,
                        "dig_gain": 0
                },
                "tx_lut_15": {
                        "desc": "TX gain table, index 15",
                        "pa_gain": 3,
                        "mix_gain": 14,
                        "rf_power": 27,
                        "dig_gain": 0
                }
    },

    "gateway_conf": {
        "gateway_ID": "AA555A0000000000",
        /* change with default server address/ports, or overwrite in local_conf.json */
        "server_address": "192.168.0.17",
        "serv_port_up": 1680,
        "serv_port_down": 1680,
        /* adjust the following parameters for your network */
        "keepalive_interval": 10,
        "stat_interval": 30,
        "push_timeout_ms": 100,
        /* forward only valid packets */
        "forward_crc_valid": true,
        "forward_crc_error": false,
        "forward_crc_disabled": false
    }
}
````

[2] logs
````
2019-01-28 20:48:15.193 Statistic: {"stat":{"time":"2019-01-28 20:48:15 GMT","rxnb":1,"rxok":1,"rxfw":1,"ackr":100.0,"dwnb":0,"txnb":0}}
2019-01-28 20:48:34.087 Physical dataUp {"rxpk":[{"tmst":3869713428,"chan":7,"rfch":1,"freq":903.700000,"stat":1,"modu":"LORA","datr":"SF9BW125","codr":"4/5","lsnr":12.5,"rssi":-32,"size":23,"data":"AAMAABECxSYsQAMGEQJ3SgAzh8+51yM="}]}
2019-01-28 20:48:34.088 004A770211060340: join request received
2019-01-28 20:48:34.088 004A770211060340: querying the registry for device key
2019-01-28 20:48:34.245 004A770211060340: using edgeHub local queue
2019-01-28 20:48:34.246 004A770211060340: using cached twins for OTAA device
2019-01-28 20:48:34.247 004A770211060340: saving join properties twins
2019-01-28 20:48:35.568 004A770211060340: done saving join properties twins
2019-01-28 20:48:35.569 4B914702: JoinAccept {"txpk":{"imme":false,"data":"INMnrTn9EvAi2JyiaW93klU=","tmst":3874713428,"size":17,"freq":927.5,"rfch":0,"modu":"LORA","datr":"SF11BW500","codr":"4/5","powe":14,"ipol":true}}
2019-01-28 20:48:35.569 004A770211060340: join accept sent with ID B873
2019-01-28 20:48:35.569 004A770211060340: processing time: 00:00:01.4818369
2019-01-28 20:48:35.570 Packet with id B873 successfully transmitted by the aggregator
2019-01-28 20:48:41.379 Physical dataUp {"rxpk":[{"tmst":3877001644,"chan":8,"rfch":0,"freq":903.000000,"stat":1,"modu":"LORA","datr":"SF8BW500","codr":"4/5","lsnr":10.2,"rssi":-34,"size":23,"data":"AAMAABECxSYsQAMGEQJ3SgCJRmabVd8="}]}
2019-01-28 20:48:41.379 004A770211060340: join request received
2019-01-28 20:48:41.380 004A770211060340: querying the registry for device key
2019-01-28 20:48:41.441 004A770211060340: using edgeHub local queue
2019-01-28 20:48:41.441 004A770211060340: using cached twins for OTAA device
2019-01-28 20:48:41.445 004A770211060340: saving join properties twins
2019-01-28 20:48:41.701 004A770211060340: done saving join properties twins
2019-01-28 20:48:41.706 Error processing the message The given key '6' was not present in the dictionary.,    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LoRaTools.Regions.Region.GetDownstreamDR(Rxpk upstreamChannel) in /app/LoraTools/Regions/Region.cs:line 137
   at LoRaWan.NetworkServer.MessageProcessor.ProcessJoinRequest(LoRaMessageWrapper loraMessage) in /app/LoRaWan.NetworkServer/MessageProcessor.cs:line 613
   at LoRaWan.NetworkServer.MessageProcessor.ProcessMessageAsync(Byte[] message) in /app/LoRaWan.NetworkServer/MessageProcessor.cs:line 55
   at LoRaWan.NetworkServer.UdpServer.<>c__DisplayClass10_1.<<RunUdpListener>b__0>d.MoveNext() in /app/LoRaWan.NetworkServer/UdpServer.cs:line 105
2019-01-28 20:48:45.194 Statistic: {"stat":{"time":"2019-01-28 20:48:45 GMT","rxnb":2,"rxok":2,"rxfw":2,"ackr":100.0,"dwnb":1,"txnb":1}}
2019-01-28 20:48:49.525 Physical dataUp {"rxpk":[{"tmst":3885147356,"chan":5,"rfch":1,"freq":903.300000,"stat":1,"modu":"LORA","datr":"SF9BW125","codr":"4/5","lsnr":12.5,"rssi":-34,"size":23,"data":"AAMAABECxSYsQAMGEQJ3SgB7totqHk0="}]}
2019-01-28 20:48:49.526 004A770211060340: join request received
2019-01-28 20:48:49.526 004A770211060340: querying the registry for device key
2019-01-28 20:48:49.579 004A770211060340: using edgeHub local queue
2019-01-28 20:48:49.579 004A770211060340: using cached twins for OTAA device
2019-01-28 20:48:49.580 004A770211060340: saving join properties twins
2019-01-28 20:48:49.851 004A770211060340: done saving join properties twins
2019-01-28 20:48:49.852 9F0E6502: JoinAccept {"txpk":{"imme":false,"data":"IJlFzfXgCeAEZ9kN2N7rtuQ=","tmst":3890147356,"size":17,"freq":926.3,"rfch":0,"modu":"LORA","datr":"SF11BW500","codr":"4/5","powe":14,"ipol":true}}
2019-01-28 20:48:49.853 004A770211060340: join accept sent with ID 28CD
2019-01-28 20:48:49.853 004A770211060340: processing time: 00:00:00.3283120
2019-01-28 20:48:49.855 Packet with id 28CD successfully transmitted by the aggregator
````

**Comment by ronniesa** [comment]
It seems a bug from our side on how we set the downstream data rate but we need a bit of time to investigate on the issue. 
Just to be sure you did not change the global_config from your working solution?

We keep you up to date.

**Comment by gerfen** [comment]
@ronniesa I just confirmed that the global_conf.us..config file is the same as that in the head.  Please let me know if I can provide anymore information.

![image](https://user-images.githubusercontent.com/5280484/51907774-aef94780-237c-11e9-9f28-4a8b0aa05bd5.png)

**Comment by ronniesa** [comment]
Yep, is in our part the bug. We will probably have a fix at the beginning of next week

**Comment by gerfen** [comment]
I received another set of devices from a different manufacturer yesterday and just had a chance to set them up this morning.  They fail to join the network as well but with a different error message[1].

I've doubled checked the AppKey and the AppEUI to confirm they are correct.  Is this related to the same bug?

Thanks.

[1] Logs
````
2019-01-29 16:59:36.959 Physical dataUp {"rxpk":[{"tmst":3518102372,"chan":5,"rfch":1,"freq":903.300000,"stat":1,"modu":"LORA","datr":"SF10BW125","codr":"4/5","lsnr":12.5,"rssi":-25,"size":23,"data":"AAAAAAAQehMAMygAABB6EwD/LmeVGGw="}]}
2019-01-29 16:59:36.959 00137A1000002833: join request received
2019-01-29 16:59:36.960 00137A1000002833: querying the registry for device key
2019-01-29 16:59:37.014 00137A1000002833: using edgeHub local queue
2019-01-29 16:59:37.015 00137A1000002833: using cached twins for OTAA device
2019-01-29 16:59:37.015 00137A1000002833: AppEUI for OTAA does not match for device
2019-01-29 16:59:37.016 00137A1000002833: join request refused
2019-01-29 16:59:37.016 00137A1000002833: processing time: 00:00:00.0572299
2019-01-29 16:59:46.465 Statistic: {"stat":{"time":"2019-01-29 16:59:46 GMT","rxnb":3,"rxok":2,"rxfw":2,"ackr":100.0,"dwnb":0,"txnb":0}}
2019-01-29 17:00:16.461 Statistic: {"stat":{"time":"2019-01-29 17:00:16 GMT","rxnb":0,"rxok":0,"rxfw":0,"ackr":100.0,"dwnb":0,"txnb":0}}
````

**Comment by ronniesa** [comment]
Some devices like the ones that use LMIC lib expect the key entered reversed (little endian) this could be the issue. Are the devices the same or just same manufacturer? You can try to reverse the AppEUI on the device and see if the problem persist.

**Comment by gerfen** [comment]
They are the same device.  I tried to clear the cache on the gateway but that didn't seem to have any effect.

**Comment by gerfen** [comment]
I tried to reverse the AppEUI for my failing device but it still fails[1]
.  FWIW, I have been chatting with @Mandur and we have introduced a change to the Region class which allows more sensors  from one manufactuere to successfully join but not the other.  The changes to REgion.cs that I have deployed are here:  https://github.com/Azure/iotedge-lorawan-starterkit/tree/mik-dev-0.3.0-preview-us-dr-fix.  

FWIW, The change to Region.cs has allowed one of my ThingsNode sensors which previously required me to change the entire frequency plan for the gateway to suddenly start connecting albeit with a symmetrical AppKey and AppEUI.  

Let me know if there is some other experiment you would like me to try.

````
2019-01-30 21:55:59.246 Facade function url: https://evolutioniothubfunction.azurewebsites.net/api/
2019-01-30 21:55:59.556 LoRaWAN server started on port 1680
2019-01-30 21:56:21.500 Statistic: {"stat":{"time":"2019-01-30 21:56:21 GMT","rxnb":0,"rxok":0,"rxfw":0,"ackr":100.0,"dwnb":0,"txnb":0}}
2019-01-30 21:56:29.983 Physical dataUp {"rxpk":[{"tmst":2251176527,"chan":8,"rfch":0,"freq":903.000000,"stat":1,"modu":"LORA","datr":"SF8BW500","codr":"4/5","lsnr":10.0,"rssi":-34,"size":23,"data":"AAMAABECxSYsQAMGEQJ3SgD4NJtaemI="}]}
2019-01-30 21:56:30.124 004A770211060340: join request received
2019-01-30 21:56:30.164 004A770211060340: querying the registry for device key
2019-01-30 21:56:30.994 004A770211060340: using edgeHub local queue
2019-01-30 21:56:31.043 004A770211060340: getting twins for OTAA for device
2019-01-30 21:56:31.048 004A770211060340: getting twins
2019-01-30 21:56:38.141 Physical dataUp {"rxpk":[{"tmst":2259333596,"chan":6,"rfch":1,"freq":903.500000,"stat":1,"modu":"LORA","datr":"SF9BW125","codr":"4/5","lsnr":12.8,"rssi":-35,"size":23,"data":"AAMAABECxSYsQAMGEQJ3SgD/ed0xw5I="}]}
2019-01-30 21:56:38.141 004A770211060340: join request received
2019-01-30 21:56:38.141 004A770211060340: querying the registry for device key
2019-01-30 21:56:38.240 004A770211060340: using edgeHub local queue
2019-01-30 21:56:38.242 004A770211060340: getting twins for OTAA for device
2019-01-30 21:56:38.243 004A770211060340: getting twins
2019-01-30 21:56:45.935 Physical dataUp {"rxpk":[{"tmst":2267134403,"chan":8,"rfch":0,"freq":903.000000,"stat":1,"modu":"LORA","datr":"SF8BW500","codr":"4/5","lsnr":9.5,"rssi":-34,"size":23,"data":"AAMAABECxSYsQAMGEQJ3SgCiGiICwIA="}]}
2019-01-30 21:56:45.935 004A770211060340: join request received
2019-01-30 21:56:45.935 004A770211060340: querying the registry for device key
2019-01-30 21:56:46.052 004A770211060340: using edgeHub local queue
2019-01-30 21:56:46.053 004A770211060340: getting twins for OTAA for device
2019-01-30 21:56:46.054 004A770211060340: getting twins
2019-01-30 21:56:51.465 Statistic: {"stat":{"time":"2019-01-30 21:56:51 GMT","rxnb":3,"rxok":3,"rxfw":3,"ackr":100.0,"dwnb":0,"txnb":0}}
2019-01-30 21:56:54.099 Physical dataUp {"rxpk":[{"tmst":2275290980,"chan":5,"rfch":1,"freq":903.300000,"stat":1,"modu":"LORA","datr":"SF9BW125","codr":"4/5","lsnr":12.8,"rssi":-36,"size":23,"data":"AAMAABECxSYsQAMGEQJ3SgDkrafgABg="}]}
2019-01-30 21:56:54.099 004A770211060340: join request received
2019-01-30 21:56:54.099 004A770211060340: querying the registry for device key
2019-01-30 21:56:54.162 004A770211060340: using edgeHub local queue
2019-01-30 21:56:54.163 004A770211060340: getting twins for OTAA for device
2019-01-30 21:56:54.163 004A770211060340: getting twins
2019-01-30 21:57:01.891 Physical dataUp {"rxpk":[{"tmst":2283091295,"chan":8,"rfch":0,"freq":903.000000,"stat":1,"modu":"LORA","datr":"SF8BW500","codr":"4/5","lsnr":10.5,"rssi":-36,"size":23,"data":"AAMAABECxSYsQAMGEQJ3SgDxW4PDWG0="}]}
2019-01-30 21:57:01.891 004A770211060340: join request received
2019-01-30 21:57:01.891 004A770211060340: querying the registry for device key
2019-01-30 21:57:02.017 004A770211060340: using edgeHub local queue
2019-01-30 21:57:02.018 004A770211060340: getting twins for OTAA for device
2019-01-30 21:57:02.018 004A770211060340: getting twins
2019-01-30 21:57:11.346 004A770211060340: done getting twins
2019-01-30 21:57:11.351 004A770211060340: done getting twins
2019-01-30 21:57:11.352 004A770211060340: done getting twins
2019-01-30 21:57:11.359 004A770211060340: done getting twins
2019-01-30 21:57:11.446 004A770211060340: done getting twins for OTAA device
2019-01-30 21:57:11.448 004A770211060340: done getting twins for OTAA device
2019-01-30 21:57:11.449 004A770211060340: done getting twins for OTAA device
2019-01-30 21:57:11.450 004A770211060340: done getting twins for OTAA device
2019-01-30 21:57:11.657 004A770211060340: processing of the join request took too long, sending no message
2019-01-30 21:57:11.657 004A770211060340: processing of the join request took too long, sending no message
2019-01-30 21:57:11.658 004A770211060340: processing of the join request took too long, sending no message
2019-01-30 21:57:11.659 004A770211060340: processing of the join request took too long, sending no message
2019-01-30 21:57:11.664 004A770211060340: saving join properties twins
2019-01-30 21:57:11.664 004A770211060340: saving join properties twins
2019-01-30 21:57:11.665 004A770211060340: saving join properties twins
2019-01-30 21:57:11.665 004A770211060340: saving join properties twins
2019-01-30 21:57:12.260 004A770211060340: done saving join properties twins
2019-01-30 21:57:12.380 Error processing the message The given key '6' was not present in the dictionary.,    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LoRaTools.Regions.Region.GetDownstreamDR(Rxpk upstreamChannel) in /app/LoraTools/Regions/Region.cs:line 137
   at LoRaWan.NetworkServer.MessageProcessor.ProcessJoinRequest(LoRaMessageWrapper loraMessage) in /app/LoRaWan.NetworkServer/MessageProcessor.cs:line 613
   at LoRaWan.NetworkServer.MessageProcessor.ProcessMessageAsync(Byte[] message) in /app/LoRaWan.NetworkServer/MessageProcessor.cs:line 55
   at LoRaWan.NetworkServer.UdpServer.<>c__DisplayClass10_1.<<RunUdpListener>b__0>d.MoveNext() in /app/LoRaWan.NetworkServer/UdpServer.cs:line 105
2019-01-30 21:57:13.449 004A770211060340: done getting twins
2019-01-30 21:57:13.449 004A770211060340: done getting twins for OTAA device
2019-01-30 21:57:13.451 004A770211060340: AppEUI for OTAA does not match for device
2019-01-30 21:57:13.451 004A770211060340: join request refused
2019-01-30 21:57:13.451 004A770211060340: processing time: 00:00:27.5165218
2019-01-30 21:57:14.505 004A770211060340: done saving join properties twins
2019-01-30 21:57:14.507 004A770211060340: processing of the join request took too long, using second join accept receive window
2019-01-30 21:57:14.507 004A770211060340: using standard second receive windows for join request
2019-01-30 21:57:14.551 F84C9402: JoinAccept {"txpk":{"imme":false,"data":"IJ50WaOxFRHrxLUCQzmCJq0=","tmst":2281290980,"size":17,"freq":923.3,"rfch":0,"modu":"LORA","datr":"SF12BW500","codr":"4/5","powe":14,"ipol":true}}
2019-01-30 21:57:14.559 004A770211060340: join accept sent with ID DE08
2019-01-30 21:57:14.559 004A770211060340: processing time: 00:00:20.4608261
2019-01-30 21:57:14.561 Packet with id DE08 had a problem to be transmitted over the air :{"txpk_ack":{"error":"TOO_EARLY"}}
2019-01-30 21:57:15.727 004A770211060340: could not save twins with error: Operation timeout expired.
2019-01-30 21:57:15.727 004A770211060340: could not save twins with error: Operation timeout expired.
2019-01-30 21:57:15.727 004A770211060340: join request could not save twins, join refused
2019-01-30 21:57:15.727 004A770211060340: join request could not save twins, join refused
2019-01-30 21:57:21.462 Statistic: {"stat":{"time":"2019-01-30 21:57:21 GMT","rxnb":3,"rxok":2,"rxfw":2,"ackr":100.0,"dwnb":1,"txnb":0}}
2019-01-30 21:57:51.466 Statistic: {"stat":{"time":"2019-01-30 21:57:51 GMT","rxnb":0,"rxok":0,"rxfw":0,"ackr":100.0,"dwnb":0,"txnb":0}}
````

**Comment by ronniesa** [comment]
I belive AppEUI and DevEUI need to be reversed but not AppKey for devices that are little endians

**Comment by Mandur** [comment]
This was due to a wrong implementation in data rate mapping in US region. I will investigate to see if there are other glitches next week. 
@gerfen thank you for your continuous support in the project! Let us know if this issue still occur in some cases or if there are other problems rising in the US region.

**Comment by gerfen** [comment]
I received the following information from the manufactuer:  "The device is big endian,and based on loramac-node,not lmic".  So I think there's still some work to do with mapping the frequencies correctly for the US frequency plan.  I'm willing to help out however I can to get this resolved.

**Comment by Mandur** [comment]
@gerfen if you could try the new branch and see if the issue occurs again, that would be great!

**Comment by Mandur** [comment]
After the remote session we were able to join the additional device. It was as expected probably an endianess problem. 
@gerfen please let us know if you encounter any other issues in the US frequencies & thank you for your help
