### ISSUE TITLE
Issue with LoRaWanNetworkSrvModule

### ISSUE THREAD

**Issue by maxstefaniv** [Azure/iotedge-lorawan-starterkit#293]
Got this issue out of nowhere. Saved logs in support_bundle.zip
Restarting edge fixed it.

## Expected Behavior
No errors, as I am not doing communication with devices, only receiving telemetry.

## Current Behavior
```
2021-05-13 07:01:51.477 0100DA30: LoRaTools.Mac.MacCommandException: The Mac Command was not well formed, aborting mac command processing
   at LoRaTools.MacCommand..ctor(ReadOnlySpan`1 input) in /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/MACCommand.cs:line 35
   at LoRaTools.RXParamSetupAnswer..ctor(ReadOnlySpan`1 readOnlySpan) in /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/RXParamSetupAnswer.cs:line 35
   at LoRaTools.MacCommand.CreateMacCommandFromBytes(String deviceId, ReadOnlyMemory`1 input) in /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Mac/MACCommand.cs:line 76
```

## Context (Environment)
All data in uploaded .zip

[support_bundle.zip](https://github.com/Azure/iotedge-lorawan-starterkit/files/6472665/support_bundle.zip)

**Comment by Mandur** [comment]
Hello @maxstefaniv 

Thank you for raising the issue. I managed to isolate the message triggering the behavior. This is a particular malformed message that doesn't follow the lorawan specs.
Due to a missplaced catch clause in our code, we kept processing the message indefinitely. This is now fixed. We will release a new version in the next days encompassing all these fixes
