### ISSUE TITLE
Error on receiving message in LoRaWanNetworkSrvModule (EU868)

### ISSUE THREAD

**Issue by thomasvoorend** [Azure/iotedge-lorawan-starterkit#85]
Hi, 
After some messages arrived at the LoRaWanNetworkSrvModule on the IoT edge, a error like this will be shown, does anyone have any idea what the cause of this error is?

```
2019-01-17 10:18:13.561 Statistic: {"stat":{"time":"2019-01-17 10:18:13 GMT","rxnb":1,"rxok":1,"rxfw":1,"ackr":0.0,"dwnb":0,"txnb":0,"ping":10}}
2019-01-17 10:18:26.830 Physical dataUp {"rxpk":[{"tmst":1155992083,"time":"2019-01-17T10:18:26Z","chan":4,"rfch":0,"freq":867.900000,"stat":1,"modu":"LORA","datr":"SF7BW125","codr":"4/5","lsnr":10.2,"rssi":-61,"size":32,"data":"XXXX"}]}
2019-01-17 10:18:26.917 Error processing the message No such device or address,    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LoRaWan.NetworkServer.LoraDeviceInfoManager.GetLoraDeviceInfoAsync(String DevAddr, String GatewayId) in /app/LoRaWan.NetworkServer/LoraDeviceInfoManager.cs:line 75
   at LoRaWan.NetworkServer.MessageProcessor.ProcessLoraMessage(LoRaMessageWrapper loraMessage) in /app/LoRaWan.NetworkServer/MessageProcessor.cs:line 87
   at LoRaWan.NetworkServer.MessageProcessor.ProcessMessageAsync(Byte[] message) in /app/LoRaWan.NetworkServer/MessageProcessor.cs:line 52


```

**Comment by ronniesa** [comment]
Which preview version are you using? 0.2.0, 0.3.0? 

The error is related to the fact that the function is not finding that devAddr in the twin of the device in IoT Hub registry. But it should not throw an error but just log the info that this device is not found like in case of a device that is not yours. So we need to check what is wrong.

Are your devices working correctly are all packets throw this error?

**Comment by ronniesa** [comment]
Ok make sense we have improved the error/info from the function on 0.3. 
My guess is that you are using an LMIC based device that expect the keys and devAddr to be reversed. https://www.thethingsnetwork.org/forum/t/over-the-air-activation-otaa-with-lmic/1921/3  
The easiest way to test is to provision a new device with the key ids etc "symmetrical" just for test e.g. 

ABP:

DeviceId CC000000000000CC

"AppSKey": "CC0000000000000000000000000000CC",
"NwkSKey": "CC0000000000000000000000000000CC",
"DevAddr": "CC0000CC",

OTAA

DeviceId CC000000000000CC

"AppEUI": "CC000000000000CC",
"AppKey": "CC0000000000000000000000000000CC",

**Comment by ronniesa** [comment]
Can you check the log of the Azure Function it looks like the function cannot connect to iot hub.... you can also double check the connection string on the settings of the function

**Comment by Mandur** [comment]
Hello, 
Just to check, is the function url string is looking to something like this https://XXX.azurewebsites.net/api/ ?

**Comment by thomasvoorend** [comment]
Thanks! The /api/ was missing at my deployment. 

The Function app logs are now giving:
`2019-01-22T13:45:57.444 [Information] Executing 'GetDevice' (Reason='This function was programmatically called via the host APIs.', Id=25e10918-58b9-4f71-ac11-4b30cecbf0de)
2019-01-22T13:45:57.487 [Error] Executed 'GetDevice' (Failed, Id=25e10918-58b9-4f71-ac11-4b30cecbf0de)
The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
`

**Comment by Mandur** [comment]
After thinking more of the issue we could probably solve it faster with a live session. In case you would like to please drop me an email at chmikhai at Microsoft dot Com.

**Comment by thomasvoorend** [comment]
With special thanks to Mandur the problem is solved. The last error was due to a small mistake in the IoTHubConnectionString in the Façade application.
